x-app: &app
  build:
    context: ..
    dockerfile: docker/Dockerfile
  volumes:
    - ../data:/app/data

services:
  api:
    <<: *app
    container_name: agpw_api
    ports:
      - "8000:8000"

  worker:
    <<: *app
    container_name: agpw_worker
    command: ["uv", "run", "agent/worker.py"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
